[supervisord]
nodaemon=true

[program:postgres]
command=/usr/bin/postgres -D /var/lib/postgresql/data
environment=POSTGRES_DB=tarifadb,POSTGRES_USER=postgres,POSTGRES_PASSWORD=123
autostart=true
autorestart=true

[program:api]
command=java -jar /app/app.jar
autostart=true
autorestart=true
