[supervisord]
nodaemon=true

[program:postgres]
command=/usr/lib/postgresql/16/bin/postgres -D /var/lib/postgresql/data
autostart=true
autorestart=true
user=postgres

[program:api]
command=java -jar /app/app.jar
autostart=true
autorestart=true
