spring:
  application:
    name: api-tabela-tarifaria

  datasource:
    url: jdbc:postgresql://localhost:5432/tarifadb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
